<?php 
// ------- IMPORTANT ----- Only run this file once!
//This document creates 6 mysql database tables for the XMl system - boatdetails, descriptions, images, videos, features, engines. All are linked by BoatID
require("../classes/db.class.php");
$db = new db();

//Create Boat Details Table
$query = "CREATE TABLE boatdetails (
 BoatID int(10) NOT NULL,
 Added date NOT NULL,
 NewUsed char(4) character set utf8 default NULL,
 Make varchar(100) character set utf8 NOT NULL,
 Model varchar(100) character set utf8 NOT NULL,
 MakeModel varchar(200) character set utf8 NOT NULL,
 Length float NOT NULL,
 LengthUnit float NOT NULL,
 Length_ft float NOT NULL,
 Length_mt float NOT NULL,
 LOA float default NULL,
 LOAUnit varchar(10) character set utf8 default NULL,
 LWL float default NULL,
 LWLUnit varchar(10) character set utf8 default NULL,
 Year year(4) NOT NULL,
 Price int(11) NOT NULL,
 PriceHide text character set utf8 NOT NULL,
 PriceCurrency char(3) character set utf8 NOT NULL,
 Savings text character set utf8 NOT NULL,
 IncludedOptionsPrice text character set utf8 NOT NULL,
 FreightPrice text character set utf8 NOT NULL,
 PrepPrice text character set utf8 NOT NULL,
 TotalPrice text character set utf8 NOT NULL,
 TaxStatus varchar(20) character set utf8 NOT NULL,
 Fuel varchar(15) character set utf8 NOT NULL,
 HullMaterial varchar(20) character set utf8 NOT NULL,
 Keel varchar(15) character set utf8 NOT NULL,
 Designer varchar(50) character set utf8 default NULL,
 Builder varchar(50) character set utf8 default NULL,
 Name varchar(50) character set utf8 default NULL,
 Status varchar(15) character set utf8 default NULL,
 StockNo varchar(10) character set utf8 default NULL,
 Coop char(5) character set utf8 default NULL,
 Category varchar(50) character set utf8 NOT NULL,
 Class varchar(50) character set utf8 NOT NULL,
 Description text character set utf8 NOT NULL,
 LocationCountry char(100) character set utf8 NOT NULL,
 LocationCity varchar(40) character set utf8 NOT NULL,
 LocationState varchar(20) character set utf8 default NULL,
 Company varchar(30) character set utf8 NOT NULL,
 OfficeID mediumint(9) default NULL,
 OfficeCity mediumint(9) default NULL,
 OfficeState mediumint(9) default NULL,
 BrokerName varchar(30) character set utf8 NOT NULL,
 BrokerEmail varchar(40) character set utf8 NOT NULL,
 BrokerTel varchar(20) character set utf8 NOT NULL,
 BrokerFax varchar(20) character set utf8 default NULL,
 Beam float default NULL,
 BeamUnit varchar(10) character set utf8 default NULL,
 BridgeClearance float default NULL,
 BridgeClearanceUnit varchar(10) character set utf8 default NULL,
 MinDraft float default NULL,
 MinDraftUnit varchar(10) character set utf8 default NULL,
 MaxDraft float default NULL,
 MaxDraftUnit varchar(10) character set utf8 default NULL,
 CabinHeadroom float default NULL,
 CabinHeadroomUnit varchar(10) character set utf8 default NULL,
 Freeboard float default NULL,
 FreeboardUnit varchar(10) character set utf8 default NULL,
 DryWeight float default NULL,
 DryWeightUnit varchar(10) character set utf8 default NULL,
 Ballast float default NULL,
 BallastUnit varchar(10) character set utf8 default NULL,
 Displacement float default NULL,
 DisplacementUnit varchar(10) character set utf8 default NULL,
 CruisingSpeed smallint(6) default NULL,
 CruisingSpeedUnit varchar(10) character set utf8 default NULL,
 MaxSpeed smallint(6) default NULL,
 MaxSpeedUnit varchar(10) character set utf8 default NULL,
 FuelTankCap smallint(6) default NULL,
 FuelTankCapUnit varchar(10) character set utf8 default NULL,
 FuelTankNo tinyint(4) default NULL,
 WaterTankCap smallint(6) default NULL,
 WaterTankCapUnit varchar(10) character set utf8 default NULL,
 WaterTankNo tinyint(4) default NULL,
 HoldingTankCap smallint(6) default NULL,
 HoldingTankCapUnit varchar(10) character set utf8 default NULL,
 HoldingTankNo tinyint(4) default NULL,
 SingleBerthNo tinyint(4) default NULL,
 DoubleBerthNo tinyint(4) default NULL,
 TwinBerthNo tinyint(4) default NULL,
 CabinNo tinyint(4) default NULL,
 BathroomNo tinyint(4) default NULL,
 HeadNo tinyint(4) default NULL,
 SalesMessage text character set utf8 NOT NULL,
 PRIMARY KEY  (BoatID),
 FULLTEXT KEY MakeModel (MakeModel),
 SeatingCapacity text character set utf8 NOT NULL,
 Windlass text character set utf8 NOT NULL,
 LifeRaftCapacity text character set utf8 NOT NULL,
 Deadrise text character set utf8 NOT NULL,
 ElectricalCircut text character set utf8 NOT NULL,
 TrimTabs text character set utf8 NOT NULL,
 RangeMeasure text character set utf8 NOT NULL,
 RangeUnit text character set utf8 NOT NULL,
 SalesRepID text character set utf8 NOT NULL,
 DriveType text character set utf8 NOT NULL,
 NotForSale text character set utf8 NOT NULL,
 YWID text character set utf8 NOT NULL,
 TradeIn text character set utf8 NOT NULL,
 EngineType text character set utf8 NOT NULL
)";
$result = $db->db_query($query);
if (!$result) die ("Database access failed1");

//Create Descriptions Table
$query = "CREATE TABLE descriptions (
	BoatID INT NOT NULL,
	AddTitle VARCHAR(150) CHARACTER SET utf8 NOT NULL,
	AddDescription TEXT CHARACTER SET utf8 NOT NULL
		)";
	
$result = $db->db_query($query);
if (!$result) die ("Database access failed2");

//Create Images Table
$query = "CREATE TABLE images (
	BoatID INT NOT NULL,
	ImageURL VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	ImageRanking CHAR(2) CHARACTER SET utf8 NOT NULL,
	ImageTitle VARCHAR(150) CHARACTER SET utf8 NOT NULL
		)";
	
$result = $db->db_query($query);
if (!$result) die ("Database access failed3");

//Create Videos Table
$query = "CREATE TABLE videos (
	BoatID INT NOT NULL,
	VideoURL VARCHAR(150) CHARACTER SET utf8 NOT NULL,
	VideoTitle VARCHAR(150) CHARACTER SET utf8 NOT NULL,
	VideoThumb VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	VideoBrochure VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	NumericPriority VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	VideoDescription VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	UniqueMediaURL VARCHAR(150) CHARACTER SET utf8 NOT NULL,
	UniqueMediaTitle VARCHAR(150) CHARACTER SET utf8 NOT NULL,
	VideoEmbed TEXT CHARACTER SET utf8 NOT NULL

		)";
	
$result = $db->db_query($query);
if (!$result) die ("Database access failed4");

//Create Features Table
$query = "CREATE TABLE features (
	BoatID INT NOT NULL,
	Feature VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	FeatureDetails VARCHAR(250) CHARACTER SET utf8 NOT NULL
		)";

$result = $db->db_query($query);
if (!$result) die ("Database access failed5");

//Create Engines Table
$query = "CREATE TABLE engines (
	BoatID INT NOT NULL,
	EngineMake VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	EngineModel VARCHAR(100) CHARACTER SET utf8 NOT NULL,
	EngineYear YEAR NOT NULL,
	EngineFuel VARCHAR(20) CHARACTER SET utf8 NOT NULL,
	EngineNo CHAR(2) CHARACTER SET utf8 NOT NULL,
	TotalPower SMALLINT NOT NULL,
	TotalPowerUnit VARCHAR(10) CHARACTER SET utf8 NOT NULL,
	PropellerType VARCHAR(30) CHARACTER SET utf8 NOT NULL,
	EngineTankMaterial VARCHAR(30) CHARACTER SET utf8 NOT NULL,
	DriveType VARCHAR(30) CHARACTER SET utf8 NOT NULL,
	HorsePower SMALLINT NOT NULL,
    HorsePowerUnit VARCHAR(10) CHARACTER SET utf8 NOT NULL,
	EngineHours  VARCHAR(30) CHARACTER SET utf8 NOT NULL
		)";

$result = $db->db_query($query);
if (!$result) die ("Database access failed6");


	

//Create lookup_feature_translations Table
$query = "create table lookup_feature_translations (
  `translation_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `key_text` varchar(100) NOT NULL,
  `language_name` char(2) NOT NULL,
  `translated_value` text,
  PRIMARY KEY  (`translation_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;";

$result = $db->db_query($query);
if (!$result) die ("Database access failed7");

//Create lookup_features Table
$query = "CREATE TABLE `lookup_features` (
  `feature_id` mediumint(9) NOT NULL default '0',
  `feature_category_id` smallint(6) NOT NULL default '0',
  `label_name` varchar(200) NOT NULL default '',
  `sort_order` smallint(6) NOT NULL default '0',
  `obsolete_ind` tinyint(4) NOT NULL default '0',
  `power_ind` tinyint(4) NOT NULL default '0',
  `sail_ind` tinyint(4) NOT NULL default '0',
  `key_text` varchar(100) default NULL,
  PRIMARY KEY  (`feature_id`),
  KEY `features_feat_cat_id_i` (`feature_category_id`),
  KEY `feature_localizable_resource_key_text` (`key_text`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;";

$result = $db->db_query($query);
if (!$result) die ("Database access failed8");

//Create lookup_feature_categories Table
$query = "CREATE TABLE `lookup_feature_categories` (
  `feature_category_id` smallint(6) NOT NULL default '0',
  `sort_order` smallint(6) NOT NULL default '0',
  `label_name` varchar(200) NOT NULL default '',
  `power_ind` tinyint(4) NOT NULL default '0',
  `sail_ind` tinyint(4) NOT NULL default '0',
  `obsolete_ind` tinyint(4) NOT NULL default '0',
  `key_text` varchar(100) default NULL,
  PRIMARY KEY  (`feature_category_id`),
  KEY `feature_category_localizable_resource_key_text` (`key_text`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;";
	
$result = $db->db_query($query);
if (!$result) die ("Database access failed9");

$query = "insert into lookup_feature_categories
(feature_category_id,sort_order,label_name,power_ind,sail_ind,obsolete_ind,key_text)
values
('100','100','BoatName','1','1','0','ts.feature_category.BoatName'),
('101','200','Specs','1','1','0','ts.feature_category.Specs'),
('102','300','Dimensions','1','1','0','ts.feature_category.Dimensions'),
('103','400','Engines','1','1','0','ts.feature_category.Engines'),
('104','500','Tanks','1','1','0','ts.feature_category.Tanks'),
('105','600','Accommodation','1','1','0','ts.feature_category.Accommodation'),
('106','700','Electronics','1','1','0','ts.feature_category.Electronics'),
('107','800','Sails','0','1','0','ts.feature_category.Sails'),
('108','900','Rigging','0','1','0','ts.feature_category.Rigging'),
('109','1000','InsideEquipment','1','1','0','ts.feature_category.InsideEquipment'),
('110','1100','ElectricalEquipment','1','1','0','ts.feature_category.ElectricalEquipment'),
('111','1200','OutsideEquipmentExtras','1','1','0','ts.feature_category.OutsideEquipmentExtras'),
('112','1300','Covers','1','1','0','ts.feature_category.Covers'),
('113','1400','AdditionalEquipment','1','1','0','ts.feature_category.AdditionalEquipment'),
('114','1500','Disclaimer','1','1','0','ts.feature_category.Disclaimer');";

$result = $db->db_query($query);
if (!$result) die ("Database access failed10");

$query = "insert into lookup_features
(feature_id,feature_category_id,label_name,sort_order,obsolete_ind,power_ind,sail_ind,key_text)
values
('100','102','IncludesBowsprit','100','0','1','1','ts.features.IncludesBowsprit'),
('101','103','RopeCutter','100','0','1','1','ts.features.RopeCutter'),
('102','103','TrimTabs','120','0','1','1','ts.features.TrimTabs'),
('103','105','ConvertibleSaloon','110','0','1','1','ts.features.ConvertibleSaloon'),
('104','106','Depthsounder','110','0','1','1','ts.features.Depthsounder'),
('105','106','Log-speedometer','120','0','1','1','ts.features.Log-speedometer'),
('106','106','WindspeedAndDirection','130','0','1','1','ts.features.WindspeedAndDirection'),
('107','106','Repeater(s)','150','0','1','1','ts.features.Repeater(s)'),
('108','106','NavigationCenter','170','0','1','1','ts.features.NavigationCenter'),
('109','106','Plotter','190','0','1','1','ts.features.Plotter'),
('110','106','Autopilot','210','0','1','1','ts.features.Autopilot'),
('111','106','Compass','220','0','1','1','ts.features.Compass'),
('112','106','GPS','240','0','1','1','ts.features.GPS'),
('113','106','VHF','260','0','1','1','ts.features.VHF'),
('114','106','Radar','280','0','1','1','ts.features.Radar'),
('115','106','RadarDetector','290','0','1','1','ts.features.RadarDetector'),
('116','106','Computer','310','0','1','1','ts.features.Computer'),
('117','106','TVSet','320','0','1','1','ts.features.TVSet'),
('118','106','VCR','330','0','1','1','ts.features.VCR'),
('119','106','DVDPlayer','350','0','1','1','ts.features.DVDPlayer'),
('120','106','Radio','360','0','1','1','ts.features.Radio'),
('121','106','CDPlayer','380','0','1','1','ts.features.CDPlayer'),
('122','106','CockpitSpeakers','390','0','1','1','ts.features.CockpitSpeakers'),
('123','107','FullyBattenedMainsail','110','0','0','1','ts.features.FullyBattenedMainsail'),
('124','107','BattenedMainsail','140','0','0','1','ts.features.BattenedMainsail'),
('125','107','FurlingMainsail','180','0','0','1','ts.features.FurlingMainsail'),
('126','107','Genoa','210','0','0','1','ts.features.Genoa'),
('127','107','FurlingGenoa','240','0','0','1','ts.features.FurlingGenoa'),
('128','107','StormJib','280','0','0','1','ts.features.StormJib'),
('129','107','Spinnaker','310','0','0','1','ts.features.Spinnaker'),
('130','107','GennakerCruisingSpinnaker','340','0','0','1','ts.features.GennakerCruisingSpinnaker'),
('131','107','AsymetricSpinnaker','370','0','0','1','ts.features.AsymetricSpinnaker'),
('132','107','Trisail','390','0','0','1','ts.features.Trisail'),
('133','108','SteeringWheel','120','0','0','1','ts.features.SteeringWheel'),
('134','108','Tiller','130','0','0','1','ts.features.Tiller'),
('135','108','HydraulicWinch','210','0','0','1','ts.features.HydraulicWinch'),
('136','108','ElectricWinch','220','0','0','1','ts.features.ElectricWinch'),
('137','108','SpinnakerPole','310','0','0','1','ts.features.SpinnakerPole'),
('138','109','SternThruster','110','0','1','1','ts.features.SternThruster'),
('139','109','BowThruster','120','0','1','1','ts.features.BowThruster'),
('140','109','ElectricBilgePump','130','0','1','1','ts.features.ElectricBilgePump'),
('141','109','ManualBilgePump','140','0','1','1','ts.features.ManualBilgePump'),
('142','109','BatteryCharger','150','0','1','1','ts.features.BatteryCharger'),
('143','109','AirCompressor','160','0','1','1','ts.features.AirCompressor'),
('144','109','AirConditioning','210','0','1','1','ts.features.AirConditioning'),
('145','109','Heating','220','0','1','1','ts.features.Heating'),
('146','109','HotWater','230','0','1','1','ts.features.HotWater'),
('147','109','FreshWaterMaker','240','0','1','1','ts.features.FreshWaterMaker'),
('148','109','SeaWaterPump','250','0','1','1','ts.features.SeaWaterPump'),
('149','109','Dishwasher','260','0','1','1','ts.features.Dishwasher'),
('150','109','WashingMachine','270','0','1','1','ts.features.WashingMachine'),
('151','109','Oven','310','0','1','1','ts.features.Oven'),
('152','109','MicrowaveOven','320','0','1','1','ts.features.MicrowaveOven'),
('153','109','MarineHead','330','0','1','1','ts.features.MarineHead'),
('154','109','ElectricHead','340','0','1','1','ts.features.ElectricHead'),
('155','109','ChemicalHead','350','0','1','1','ts.features.ChemicalHead'),
('156','109','Refrigerator','360','0','1','1','ts.features.Refrigerator'),
('157','109','DeepFreezer','370','0','1','1','ts.features.DeepFreezer'),
('158','110','ShorePowerInlet','110','0','1','1','ts.features.ShorePowerInlet'),
('159','110','Generator','210','0','1','1','ts.features.Generator'),
('160','110','Inverter','310','0','1','1','ts.features.Inverter'),
('161','111','TeakCockpit','110','0','1','1','ts.features.TeakCockpit'),
('162','111','TeakSidedecks','120','0','1','1','ts.features.TeakSidedecks'),
('163','111','Gangway','130','0','1','1','ts.features.Gangway'),
('164','111','HydraulicGangway','150','0','1','1','ts.features.HydraulicGangway'),
('165','111','WindGenerator','150','0','1','1','ts.features.WindGenerator'),
('166','111','SolarPanel','160','0','1','1','ts.features.SolarPanel'),
('167','111','CockpitCushions','210','0','1','1','ts.features.CockpitCushions'),
('168','111','CockpitTable','220','0','1','1','ts.features.CockpitTable'),
('169','111','SwimmingLadder','230','0','1','1','ts.features.SwimmingLadder'),
('170','111','CockpitShower','240','0','1','1','ts.features.CockpitShower'),
('171','111','OutboardEngineBrackets','250','0','1','1','ts.features.OutboardEngineBrackets'),
('172','111','Davits','260','0','1','1','ts.features.Davits'),
('173','111','RadarReflector','310','0','1','1','ts.features.RadarReflector'),
('174','111','Tender','320','0','1','1','ts.features.Tender'),
('175','111','Liferaft','330','0','1','1','ts.features.Liferaft'),
('176','112','BiminiTop','110','0','1','1','ts.features.BiminiTop'),
('177','112','MainsailCover','120','0','1','1','ts.features.MainsailCover'),
('178','112','CockpitCover','210','0','1','1','ts.features.CockpitCover'),
('179','112','GenoaCover','220','0','1','1','ts.features.GenoaCover'),
('180','112','SprayHood','310','0','1','1','ts.features.SprayHood'),
('181','112','LazyBag','320','0','1','1','ts.features.LazyBag'),
('182','112','Lazyjacks','330','0','1','1','ts.features.Lazyjacks'),
('183','113','RoadTrailer','110','0','1','1','ts.features.RoadTrailer'),
('184','113','LaunchingTrailer','210','0','1','1','ts.features.LaunchingTrailer'),
('185','113','BeachingLegs','310','0','1','1','ts.features.BeachingLegs'),
('186','114','AddDisclaimer','110','0','1','1','ts.features.AddDisclaimer');";

$result = $db->db_query($query);
if (!$result) die ("Database access failed11");

$query = "insert into lookup_feature_translations (key_text,language_name,translated_value)
values
('ts.features.WindGenerator','en','Wind generator'),
('ts.features.OutboardEngineBrackets','en','Outboard engine brackets'),
('ts.features.Trisail','en','Trisail'),
('ts.features.ElectricHead','en','Electric head'),
('ts.features.CockpitSpeakers','en','Cockpit speakers'),
('ts.features.ChemicalHead','en','Chemical head'),
('ts.features.GenoaCover','en','Genoa cover'),
('ts.features.Repeater(s)','en','Repeater(s)'),
('ts.features.Tiller','en','Tiller'),
('ts.features.Inverter','en','Inverter'),
('ts.features.HydraulicWinch','en','Hydraulic winch'),
('ts.features.Radar','en','Radar'),
('ts.features.ElectricWinch','en','Electric winch'),
('ts.features.TeakCockpit','en','Teak cockpit'),
('ts.features.BatteryCharger','en','Battery charger'),
('ts.features.IncludesBowsprit','en','Includes Bowsprit'),
('ts.features.Log-speedometer','en','Log-speedometer'),
('ts.features.Heating','en','Heating'),
('ts.features.MarineHead','en','Marine head'),
('ts.features.LaunchingTrailer','en','Launching trailer'),
('ts.features.WashingMachine','en','Washing machine'),
('ts.features.Liferaft','en','Liferaft'),
('ts.features.Generator','en','Generator'),
('ts.features.SolarPanel','en','Solar panel'),
('ts.features.TeakSidedecks','en','Teak sidedecks'),
('ts.features.Dishwasher','en','Dishwasher'),
('ts.features.SteeringWheel','en','Steering wheel'),
('ts.features.VHF','en','VHF'),
('ts.features.FullyBattenedMainsail','en','Fully battened mainsail'),
('ts.features.AddDisclaimer','en','Add disclaimer'),
('ts.features.Compass','en','Compass'),
('ts.features.CockpitShower','en','Cockpit shower'),
('ts.features.SpinnakerPole','en','Spinnaker pole'),
('ts.features.VCR','en','VCR'),
('ts.features.BowThruster','en','Bow thruster'),
('ts.features.GennakerCruisingSpinnaker','en','Gennaker/Cruising spinnaker'),
('ts.features.GPS','en','GPS'),
('ts.features.BeachingLegs','en','Beaching legs'),
('ts.features.CDPlayer','en','CD player'),
('ts.features.Refrigerator','en','Refrigerator'),
('ts.features.AsymetricSpinnaker','en','Asymmetric spinnaker'),
('ts.features.HydraulicGangway','en','Hydraulic gangway'),
('ts.features.SeaWaterPump','en','Sea water pump'),
('ts.features.Spinnaker','en','Spinnaker'),
('ts.features.StormJib','en','Storm jib'),
('ts.features.LazyBag','en','Lazy bag'),
('ts.features.Genoa','en','Genoa'),
('ts.features.Davits','en','Davits'),
('ts.features.CockpitCushions','en','Cockpit cushions'),
('ts.features.RoadTrailer','en','Road trailer'),
('ts.features.ShorePowerInlet','en','Shore power inlet'),
('ts.features.CockpitTable','en','Cockpit table'),
('ts.features.DeepFreezer','en','Deep freezer'),
('ts.features.FurlingMainsail','en','Furling mainsail'),
('ts.features.AirConditioning','en','Air conditioning'),
('ts.features.SprayHood','en','Spray hood'),
('ts.features.AirCompressor','en','Air compressor'),
('ts.features.MainsailCover','en','Mainsail cover'),
('ts.features.TrimTabs','en','Trim Tabs'),
('ts.features.FurlingGenoa','en','Furling genoa'),
('ts.features.NavigationCenter','en','Navigation center'),
('ts.features.ElectricBilgePump','en','Electric bilge pump'),
('ts.features.SternThruster','en','Stern thruster'),
('ts.features.ManualBilgePump','en','Manual bilge pump'),
('ts.features.Depthsounder','en','Depthsounder'),
('ts.features.WindspeedAndDirection','en','Wind speed and direction'),
('ts.features.RopeCutter','en','Rope Cutter'),
('ts.features.CockpitCover','en','Cockpit cover'),
('ts.features.Oven','en','Oven'),
('ts.features.Gangway','en','Gangway'),
('ts.features.MicrowaveOven','en','Microwave oven'),
('ts.features.Tender','en','Tender'),
('ts.features.ConvertibleSaloon','en','Convertible Saloon'),
('ts.features.Plotter','en','Plotter'),
('ts.features.Autopilot','en','Autopilot'),
('ts.features.DVDPlayer','en','DVD player'),
('ts.features.SwimmingLadder','en','Swimming ladder'),
('ts.features.RadarReflector','en','Radar reflector'),
('ts.features.FreshWaterMaker','en','Fresh water maker'),
('ts.features.Lazyjacks','en','Lazyjacks'),
('ts.features.Radio','en','Radio'),
('ts.features.HotWater','en','Hot water'),
('ts.features.RadarDetector','en','Radar Detector'),
('ts.features.BiminiTop','en','Bimini Top'),
('ts.features.TVSet','en','TV set'),
('ts.features.BattenedMainsail','en','Battened mainsail'),
('ts.features.Computer','en','Computer'),
('ts.features.WindGenerator','uk','Wind generator'),
('ts.features.OutboardEngineBrackets','uk','Outboard engine brackets'),
('ts.features.Trisail','uk','Trisail'),
('ts.features.ElectricHead','uk','Electric head'),
('ts.features.CockpitSpeakers','uk','Cockpit speakers'),
('ts.features.ChemicalHead','uk','Chemical head'),
('ts.features.GenoaCover','uk','Genoa cover'),
('ts.features.Repeater(s)','uk','Repeater(s)'),
('ts.features.Tiller','uk','Tiller'),
('ts.features.Inverter','uk','Inverter'),
('ts.features.HydraulicWinch','uk','Hydraulic winch'),
('ts.features.Radar','uk','Radar'),
('ts.features.ElectricWinch','uk','Electric winch'),
('ts.features.TeakCockpit','uk','Teak cockpit'),
('ts.features.BatteryCharger','uk','Battery charger'),
('ts.features.IncludesBowsprit','uk','Includes Bowsprit'),
('ts.features.Log-speedometer','uk','Log-speedometer'),
('ts.features.Heating','uk','Heating'),
('ts.features.MarineHead','uk','Marine head'),
('ts.features.LaunchingTrailer','uk','Launching trailer'),
('ts.features.WashingMachine','uk','Washing machine'),
('ts.features.Liferaft','uk','Liferaft'),
('ts.features.Generator','uk','Generator'),
('ts.features.SolarPanel','uk','Solar panel'),
('ts.features.TeakSidedecks','uk','Teak sidedecks'),
('ts.features.Dishwasher','uk','Dishwasher'),
('ts.features.SteeringWheel','uk','Steering wheel'),
('ts.features.VHF','uk','VHF'),
('ts.features.FullyBattenedMainsail','uk','Fully battened mainsail'),
('ts.features.AddDisclaimer','uk','Add disclaimer'),
('ts.features.Compass','uk','Compass'),
('ts.features.CockpitShower','uk','Cockpit shower'),
('ts.features.SpinnakerPole','uk','Spinnaker pole'),
('ts.features.VCR','uk','VCR'),
('ts.features.BowThruster','uk','Bow thruster'),
('ts.features.GennakerCruisingSpinnaker','uk','Gennaker/Cruising spinnaker'),
('ts.features.GPS','uk','GPS'),
('ts.features.BeachingLegs','uk','Beaching legs'),
('ts.features.CDPlayer','uk','CD player'),
('ts.features.Refrigerator','uk','Refrigerator'),
('ts.features.AsymetricSpinnaker','uk','Asymmetric spinnaker'),
('ts.features.HydraulicGangway','uk','Hydraulic gangway'),
('ts.features.SeaWaterPump','uk','Sea water pump'),
('ts.features.Spinnaker','uk','Spinnaker'),
('ts.features.StormJib','uk','Storm jib'),
('ts.features.LazyBag','uk','Lazy bag'),
('ts.features.Genoa','uk','Genoa'),
('ts.features.Davits','uk','Davits'),
('ts.features.CockpitCushions','uk','Cockpit cushions'),
('ts.features.RoadTrailer','uk','Road trailer'),
('ts.features.ShorePowerInlet','uk','Shore power inlet'),
('ts.features.CockpitTable','uk','Cockpit table'),
('ts.features.DeepFreezer','uk','Deep freezer'),
('ts.features.FurlingMainsail','uk','Furling mainsail'),
('ts.features.AirConditioning','uk','Air conditioning'),
('ts.features.SprayHood','uk','Spray hood'),
('ts.features.AirCompressor','uk','Air compressor'),
('ts.features.MainsailCover','uk','Mainsail cover'),
('ts.features.TrimTabs','uk','Trim Tabs'),
('ts.features.FurlingGenoa','uk','Furling genoa'),
('ts.features.NavigationCenter','uk','Navigation center'),
('ts.features.ElectricBilgePump','uk','Electric bilge pump'),
('ts.features.SternThruster','uk','Stern thruster'),
('ts.features.ManualBilgePump','uk','Manual bilge pump'),
('ts.features.Depthsounder','uk','Depthsounder'),
('ts.features.WindspeedAndDirection','uk','Wind speed and direction'),
('ts.features.RopeCutter','uk','Rope Cutter'),
('ts.features.CockpitCover','uk','Cockpit cover'),
('ts.features.Oven','uk','Oven'),
('ts.features.Gangway','uk','Gangway'),
('ts.features.MicrowaveOven','uk','Microwave oven'),
('ts.features.Tender','uk','Tender'),
('ts.features.ConvertibleSaloon','uk','Convertible Saloon'),
('ts.features.Plotter','uk','Plotter'),
('ts.features.Autopilot','uk','Autopilot'),
('ts.features.DVDPlayer','uk','DVD player'),
('ts.features.SwimmingLadder','uk','Swimming ladder'),
('ts.features.RadarReflector','uk','Radar reflector'),
('ts.features.FreshWaterMaker','uk','Fresh water maker'),
('ts.features.Lazyjacks','uk','Lazyjacks'),
('ts.features.Radio','uk','Radio'),
('ts.features.HotWater','uk','Hot water'),
('ts.features.RadarDetector','uk','Radar Detector'),
('ts.features.BiminiTop','uk','Bimini Top'),
('ts.features.TVSet','uk','TV set'),
('ts.features.BattenedMainsail','uk','Battened mainsail'),
('ts.features.Computer','uk','Computer'),
('ts.features.WindGenerator','fr','Éolienne'),
('ts.features.OutboardEngineBrackets','fr','Support de moteur annexe'),
('ts.features.Trisail','fr','Voile de cap'),
('ts.features.ElectricHead','fr','WC électrique'),
('ts.features.CockpitSpeakers','fr','Haut-parleurs de cockpit'),
('ts.features.ChemicalHead','fr','WC chimique'),
('ts.features.GenoaCover','fr','Taud de génois'),
('ts.features.Repeater(s)','fr','Répétiteur(s)'),
('ts.features.Tiller','fr','Barre franche'),
('ts.features.Inverter','fr','Convertisseur'),
('ts.features.HydraulicWinch','fr','Winch hydraulique'),
('ts.features.Radar','fr','Radar'),
('ts.features.ElectricWinch','fr','Winch électrique'),
('ts.features.TeakCockpit','fr','Cockpit teck'),
('ts.features.BatteryCharger','fr','Chargeur de batteries'),
('ts.features.IncludesBowsprit','fr','Beaupré compris'),
('ts.features.Log-speedometer','fr','Loch-speedomètre'),
('ts.features.Heating','fr','Chauffage'),
('ts.features.MarineHead','fr','WC marin'),
('ts.features.LaunchingTrailer','fr','Remorque de mise à l\'eau'),
('ts.features.WashingMachine','fr','Lave linge'),
('ts.features.Liferaft','fr','Radeau de survie'),
('ts.features.Generator','fr','Générateur'),
('ts.features.SolarPanel','fr','Panneau solaire'),
('ts.features.TeakSidedecks','fr','Passavants teck'),
('ts.features.Dishwasher','fr','Lave vaisselle'),
('ts.features.SteeringWheel','fr','Barres à roue'),
('ts.features.VHF','fr','VHF'),
('ts.features.FullyBattenedMainsail','fr','Grand voile full batten'),
('ts.features.AddDisclaimer','fr','Ajouter un désistement de renonciation'),
('ts.features.Compass','fr','Compas'),
('ts.features.CockpitShower','fr','Douchette de cockpit'),
('ts.features.SpinnakerPole','fr','Tangon de spi'),
('ts.features.VCR','fr','Magnétoscope'),
('ts.features.BowThruster','fr','Propulseur d\'étrave'),
('ts.features.GennakerCruisingSpinnaker','fr','Gennaker'),
('ts.features.GPS','fr','GPS'),
('ts.features.BeachingLegs','fr','béquilles d\'échouage'),
('ts.features.CDPlayer','fr','Lecteur CD'),
('ts.features.Refrigerator','fr','Réfrigérateur'),
('ts.features.AsymetricSpinnaker','fr','Spi asymétrique'),
('ts.features.HydraulicGangway','fr','Passerelle hydraulique'),
('ts.features.SeaWaterPump','fr','Pompe à eau de mer'),
('ts.features.Spinnaker','fr','Spi symétrique'),
('ts.features.StormJib','fr','Tourmentin'),
('ts.features.LazyBag','fr','Lazy bag'),
('ts.features.Genoa','fr','Génois'),
('ts.features.Davits','fr','Bossoirs'),
('ts.features.CockpitCushions','fr','Coussins de cockpit'),
('ts.features.RoadTrailer','fr','Remorque routière'),
('ts.features.ShorePowerInlet','fr','Prise de quai'),
('ts.features.CockpitTable','fr','Table de cockpit'),
('ts.features.DeepFreezer','fr','Congélateur'),
('ts.features.FurlingMainsail','fr','Grand voile sur enrouleur'),
('ts.features.AirConditioning','fr','Air Conditionné'),
('ts.features.SprayHood','fr','Capote de descente'),
('ts.features.AirCompressor','fr','Compresseur'),
('ts.features.MainsailCover','fr','Taud de grand voile'),
('ts.features.TrimTabs','fr','Flaps'),
('ts.features.FurlingGenoa','fr','Génois sur enrouleur'),
('ts.features.NavigationCenter','fr','Centrale de navigation'),
('ts.features.ElectricBilgePump','fr','Pompe de cale électrique'),
('ts.features.SternThruster','fr','Propulseur de poupe'),
('ts.features.ManualBilgePump','fr','Pompe de cale manuelle'),
('ts.features.Depthsounder','fr','Sondeur'),
('ts.features.WindspeedAndDirection','fr','Girouette - Anémomètre'),
('ts.features.RopeCutter','fr','Coupe-orins'),
('ts.features.CockpitCover','fr','Taud de fermeture arrière'),
('ts.features.Oven','fr','Four'),
('ts.features.Gangway','fr','Passerelle'),
('ts.features.MicrowaveOven','fr','Micro-onde'),
('ts.features.Tender','fr','annexe'),
('ts.features.ConvertibleSaloon','fr','Salon transformable'),
('ts.features.Plotter','fr','Plotter'),
('ts.features.Autopilot','fr','Pilote automatique'),
('ts.features.DVDPlayer','fr','Lecteur DVD'),
('ts.features.SwimmingLadder','fr','Échelle de bain'),
('ts.features.RadarReflector','fr','Réflecteur de radar'),
('ts.features.FreshWaterMaker','fr','Déssalinisateur'),
('ts.features.Lazyjacks','fr','Lazy jack'),
('ts.features.Radio','fr','Radio'),
('ts.features.HotWater','fr','Eau chaude'),
('ts.features.RadarDetector','fr','Détecteur radar'),
('ts.features.BiminiTop','fr','Bimini Top'),
('ts.features.TVSet','fr','TV'),
('ts.features.BattenedMainsail','fr','Grand voile semi-lattée'),
('ts.features.Computer','fr','Ordinateur'),
('ts.features.WindGenerator','de','Windgenerator'),
('ts.features.OutboardEngineBrackets','de','Aussenbordmotor-Halterung'),
('ts.features.Trisail','de','Trisegel'),
('ts.features.ElectricHead','de','Elektrisches WC'),
('ts.features.CockpitSpeakers','de','Cockpit Lautsprecher'),
('ts.features.ChemicalHead','de','Chemie WC'),
('ts.features.GenoaCover','de','Genuapersenning'),
('ts.features.Repeater(s)','de','Tochtergerät(e)'),
('ts.features.Tiller','de','Pinne'),
('ts.features.Inverter','de','Wechselrichter'),
('ts.features.HydraulicWinch','de','Hydraulische Winsch'),
('ts.features.Radar','de','Radar'),
('ts.features.ElectricWinch','de','Elektrische Winsch'),
('ts.features.TeakCockpit','de','Cockpit Teak'),
('ts.features.BatteryCharger','de','Batterieladegerät'),
('ts.features.IncludesBowsprit','de','inklusive Bugsprit'),
('ts.features.Log-speedometer','de','Log'),
('ts.features.Heating','de','Heizung'),
('ts.features.MarineHead','de','Marine-WC'),
('ts.features.LaunchingTrailer','de','Sliptrailer'),
('ts.features.WashingMachine','de','Waschmaschine'),
('ts.features.Liferaft','de','Rettungsinsel'),
('ts.features.Generator','de','Generator'),
('ts.features.SolarPanel','de','Solarpaneel'),
('ts.features.TeakSidedecks','de','Teakdeck'),
('ts.features.Dishwasher','de','Geschirrspüler'),
('ts.features.SteeringWheel','de','Steuerrad'),
('ts.features.VHF','de','UKW-Funk'),
('ts.features.FullyBattenedMainsail','de','voll durchgelattetes Großsegel'),
('ts.features.AddDisclaimer','de','Haftungsausschlussklausel hinzufügen'),
('ts.features.Compass','de','Kompaß'),
('ts.features.CockpitShower','de','Cockpitdusche'),
('ts.features.SpinnakerPole','de','Spinnakerbaum'),
('ts.features.VCR','de','Videorekorder'),
('ts.features.BowThruster','de','Bugstrahlruder'),
('ts.features.GennakerCruisingSpinnaker','de','Gennaker'),
('ts.features.GPS','de','GPS'),
('ts.features.BeachingLegs','de','Transportrollen'),
('ts.features.CDPlayer','de','CD-Spieler'),
('ts.features.Refrigerator','de','Kühlschrank'),
('ts.features.AsymetricSpinnaker','de','Asymmetrischer Spinnaker'),
('ts.features.HydraulicGangway','de','Hydraulische Gangway'),
('ts.features.SeaWaterPump','de','Seewasserpumpe'),
('ts.features.Spinnaker','de','Spinnaker'),
('ts.features.StormJib','de','Sturmfock'),
('ts.features.LazyBag','de','Lazy bag'),
('ts.features.Genoa','de','Genua'),
('ts.features.Davits','de','Davits'),
('ts.features.CockpitCushions','de','Cockpitpolster'),
('ts.features.RoadTrailer','de','Straßentrailer'),
('ts.features.ShorePowerInlet','de','Landanschluß'),
('ts.features.CockpitTable','de','Cockpittisch'),
('ts.features.DeepFreezer','de','Gefrierschrank'),
('ts.features.FurlingMainsail','de','Rollgroßsegel'),
('ts.features.AirConditioning','de','Klimaanlage'),
('ts.features.SprayHood','de','Sprayhood'),
('ts.features.AirCompressor','de','Luftkompressor'),
('ts.features.MainsailCover','de','Großsegelpersenning'),
('ts.features.TrimTabs','de','Trimklappen'),
('ts.features.FurlingGenoa','de','Rollgenua'),
('ts.features.NavigationCenter','de','Navigationseinheit'),
('ts.features.ElectricBilgePump','de','Bilgepumpe elektrisch'),
('ts.features.SternThruster','de','Heckstrahlruder'),
('ts.features.ManualBilgePump','de','Bilgepumpe manuell'),
('ts.features.Depthsounder','de','Echolot'),
('ts.features.WindspeedAndDirection','de','Windmeßanlage'),
('ts.features.RopeCutter','de','Leinenabschneider'),
('ts.features.CockpitCover','de','Cockpit Persenning'),
('ts.features.Oven','de','Ofen'),
('ts.features.Gangway','de','Gangway'),
('ts.features.MicrowaveOven','de','Mikrowelle'),
('ts.features.Tender','de','Beiboot'),
('ts.features.ConvertibleSaloon','de','Umbaubarer Saloon'),
('ts.features.Plotter','de','Kartenplotter'),
('ts.features.Autopilot','de','Autopilot'),
('ts.features.DVDPlayer','de','DVD-Spieler'),
('ts.features.SwimmingLadder','de','Badeleiter'),
('ts.features.RadarReflector','de','Radarreflektor'),
('ts.features.FreshWaterMaker','de','Frischwasserbereiter'),
('ts.features.Lazyjacks','de','Lazy jacks'),
('ts.features.Radio','de','Radio'),
('ts.features.HotWater','de','Warmwasser'),
('ts.features.RadarDetector','de','Radardetektor'),
('ts.features.BiminiTop','de','Bimini Top'),
('ts.features.TVSet','de','TV'),
('ts.features.BattenedMainsail','de','Lattengroßsegel'),
('ts.features.Computer','de','Computer'),
('ts.features.WindGenerator','es','Generador de viento'),
('ts.features.OutboardEngineBrackets','es','Soporte motor fuerabordas'),
('ts.features.Trisail','es','Vela de capa'),
('ts.features.ElectricHead','es','Aseo eléctrico'),
('ts.features.CockpitSpeakers','es','Altavoces de bañera'),
('ts.features.ChemicalHead','es','Aseo chímico'),
('ts.features.GenoaCover','es','Toldo de génova'),
('ts.features.Repeater(s)','es','Repetidor(es)'),
('ts.features.Tiller','es','Timón de caña'),
('ts.features.Inverter','es','Invertor'),
('ts.features.HydraulicWinch','es','winche hidraúlico'),
('ts.features.Radar','es','Radar'),
('ts.features.ElectricWinch','es','Winche eléctrico'),
('ts.features.TeakCockpit','es','Teca en bañera'),
('ts.features.BatteryCharger','es','Cargador de baterías'),
('ts.features.IncludesBowsprit','es','Bauprés incluido'),
('ts.features.Log-speedometer','es','Corredera - Velocímetro'),
('ts.features.Heating','es','Calefacción'),
('ts.features.MarineHead','es','Aseo marino'),
('ts.features.LaunchingTrailer','es','Remolque'),
('ts.features.WashingMachine','es','Lavadora'),
('ts.features.Liferaft','es','Balsa salvavidas'),
('ts.features.Generator','es','Generador'),
('ts.features.SolarPanel','es','Panel solar'),
('ts.features.TeakSidedecks','es','Cubierta lateral en Teka'),
('ts.features.Dishwasher','es','Lava platos'),
('ts.features.SteeringWheel','es','Timón de rueda'),
('ts.features.VHF','es','VHF'),
('ts.features.FullyBattenedMainsail','es','Mayor full batten'),
('ts.features.AddDisclaimer','es','Agregar un descargo de responsabilidad'),
('ts.features.Compass','es','Compás'),
('ts.features.CockpitShower','es','Ducha de bañera'),
('ts.features.SpinnakerPole','es','Tangón de spi'),
('ts.features.VCR','es','Video'),
('ts.features.BowThruster','es','Propulsor de Proa'),
('ts.features.GennakerCruisingSpinnaker','es','Gennaker'),
('ts.features.GPS','es','GPS'),
('ts.features.BeachingLegs','es','Escoras'),
('ts.features.CDPlayer','es','Lector CD'),
('ts.features.Refrigerator','es','Frigorífico'),
('ts.features.AsymetricSpinnaker','es','Spi asimetrico'),
('ts.features.HydraulicGangway','es','Pasarela hidráulica'),
('ts.features.SeaWaterPump','es','Bomba de agua salada'),
('ts.features.Spinnaker','es','Spinnaker'),
('ts.features.StormJib','es','Foque de capa'),
('ts.features.LazyBag','es','Lazy bag'),
('ts.features.Genoa','es','Génova'),
('ts.features.Davits','es','Pescantes'),
('ts.features.CockpitCushions','es','Colchonetas de bañera'),
('ts.features.RoadTrailer','es','Remolque'),
('ts.features.ShorePowerInlet','es','Toma de puerto'),
('ts.features.CockpitTable','es','Mesa de bañera'),
('ts.features.DeepFreezer','es','Congelador'),
('ts.features.FurlingMainsail','es','Mayor enrollable'),
('ts.features.AirConditioning','es','Aire acondicionado'),
('ts.features.SprayHood','es','Capota de mal tiempo'),
('ts.features.AirCompressor','es','Compresor'),
('ts.features.MainsailCover','es','Cubierta de vela mayor'),
('ts.features.TrimTabs','es','Alerones'),
('ts.features.FurlingGenoa','es','Génova enrollable'),
('ts.features.NavigationCenter','es','Central de navegación'),
('ts.features.ElectricBilgePump','es','Bomba de achique eléctrica'),
('ts.features.SternThruster','es','Propulsión cola'),
('ts.features.ManualBilgePump','es','Bomba de achique manual'),
('ts.features.Depthsounder','es','Sonda'),
('ts.features.WindspeedAndDirection','es','Equipo de viento'),
('ts.features.RopeCutter','es','Corta cabos'),
('ts.features.CockpitCover','es','Lona cierre bañera'),
('ts.features.Oven','es','Horno'),
('ts.features.Gangway','es','Paserela'),
('ts.features.MicrowaveOven','es','Microondas'),
('ts.features.Tender','es','Auxiliar'),
('ts.features.ConvertibleSaloon','es','Salón convertible'),
('ts.features.Plotter','es','Plotter'),
('ts.features.Autopilot','es','Piloto automático'),
('ts.features.DVDPlayer','es','Lector DVD'),
('ts.features.SwimmingLadder','es','Escalera de baño'),
('ts.features.RadarReflector','es','Reflector de radar'),
('ts.features.FreshWaterMaker','es','Potabilizadora'),
('ts.features.Lazyjacks','es','Lazy jacks'),
('ts.features.Radio','es','Radio'),
('ts.features.HotWater','es','Agua caliente'),
('ts.features.RadarDetector','es','Detector de radar'),
('ts.features.BiminiTop','es','Toldo Bimini'),
('ts.features.TVSet','es','TV'),
('ts.features.BattenedMainsail','es','Mayor batten'),
('ts.features.Computer','es','Ordenador'),
('ts.features.WindGenerator','it','Elica a vento'),
('ts.features.OutboardEngineBrackets','it','Supporto motore fuoribordo'),
('ts.features.Trisail','it','Trisal'),
('ts.features.ElectricHead','it','WC elettrico'),
('ts.features.CockpitSpeakers','it','Altoparlanti  pozzetto'),
('ts.features.ChemicalHead','it','WC chimico'),
('ts.features.GenoaCover','it','Copertura genoa'),
('ts.features.Repeater(s)','it','Ripetitore(i)'),
('ts.features.Tiller','it','Timone a barra'),
('ts.features.Inverter','it','Invertitore'),
('ts.features.HydraulicWinch','it','Vericello idraulico'),
('ts.features.Radar','it','Radar'),
('ts.features.ElectricWinch','it','Vericello elettrico'),
('ts.features.TeakCockpit','it','Pozzetto teck'),
('ts.features.BatteryCharger','it','Caricabatterie'),
('ts.features.IncludesBowsprit','it','Incluso Bompresso'),
('ts.features.Log-speedometer','it','Log - Contamiglia'),
('ts.features.Heating','it','Riscaldamento'),
('ts.features.MarineHead','it','WC marino'),
('ts.features.LaunchingTrailer','it','Alaggio tender'),
('ts.features.WashingMachine','it','Lavatrice'),
('ts.features.Liferaft','it','Autogonfiabile'),
('ts.features.Generator','it','Generatore'),
('ts.features.SolarPanel','it','Pannello solare'),
('ts.features.TeakSidedecks','it','passavanti in teak'),
('ts.features.Dishwasher','it','Lavastoviglie'),
('ts.features.SteeringWheel','it','sterzo'),
('ts.features.VHF','it','VHF'),
('ts.features.FullyBattenedMainsail','it','Randa steccata'),
('ts.features.AddDisclaimer','it','Declinazione di responsabilità '),
('ts.features.Compass','it','Bussola'),
('ts.features.CockpitShower','it','Doccia di pozzetto'),
('ts.features.SpinnakerPole','it','Tangone dello spi'),
('ts.features.VCR','it','VHS'),
('ts.features.BowThruster','it','Elica di prua'),
('ts.features.GennakerCruisingSpinnaker','it','Gennaker'),
('ts.features.GPS','it','GPS'),
('ts.features.BeachingLegs','it','Puntelli'),
('ts.features.CDPlayer','it','Lettore di CD'),
('ts.features.Refrigerator','it','Frigorifero'),
('ts.features.AsymetricSpinnaker','it','Spinnaker assimetrico'),
('ts.features.HydraulicGangway','it','Passerella idraulica'),
('ts.features.SeaWaterPump','it','Pompa per acqua di mare'),
('ts.features.Spinnaker','it','Spinnaker'),
('ts.features.StormJib','it','Tormentina'),
('ts.features.LazyBag','it','Lazy bag'),
('ts.features.Genoa','it','Genoa'),
('ts.features.Davits','it','Gruette'),
('ts.features.CockpitCushions','it','Cuscineria pozzetto'),
('ts.features.RoadTrailer','it','Rimorchio stradale'),
('ts.features.ShorePowerInlet','it','Presa corrente a terra'),
('ts.features.CockpitTable','it','Tavola di pozzetto'),
('ts.features.DeepFreezer','it','Congelatore'),
('ts.features.FurlingMainsail','it','Randa avvolgibile'),
('ts.features.AirConditioning','it','Aria condizionata'),
('ts.features.SprayHood','it','Capotta antispruzzi'),
('ts.features.AirCompressor','it','Compressore'),
('ts.features.MainsailCover','it','Copertura randa'),
('ts.features.TrimTabs','it','Timone a ruota'),
('ts.features.FurlingGenoa','it','Genoa avvolgibile'),
('ts.features.NavigationCenter','it','Centro di Navigazione'),
('ts.features.ElectricBilgePump','it','Pompa di sentina elettrica'),
('ts.features.SternThruster','it','Elica di manovra poppa'),
('ts.features.ManualBilgePump','it','Pompa di sentina manuale'),
('ts.features.Depthsounder','it','Ecoscandaglio'),
('ts.features.WindspeedAndDirection','it','Stazione vento'),
('ts.features.RopeCutter','it','Lama taglialenze'),
('ts.features.CockpitCover','it','Tendalino pozzetto'),
('ts.features.Oven','it','Forno'),
('ts.features.Gangway','it','Passerella'),
('ts.features.MicrowaveOven','it','Microonde'),
('ts.features.Tender','it','Tender'),
('ts.features.ConvertibleSaloon','it','Salone trasformabile'),
('ts.features.Plotter','it','Plotter'),
('ts.features.Autopilot','it','Pilota automatico'),
('ts.features.DVDPlayer','it','Lettore di DVD'),
('ts.features.SwimmingLadder','it','Scaletta di bagno'),
('ts.features.RadarReflector','it','Riflettore radar'),
('ts.features.FreshWaterMaker','it','Dissalatore'),
('ts.features.Lazyjacks','it','Lazy jacks'),
('ts.features.Radio','it','Radio'),
('ts.features.HotWater','it','Acqua calda'),
('ts.features.RadarDetector','it','Radar Detector'),
('ts.features.BiminiTop','it','Tendalino rigido'),
('ts.features.TVSet','it','TV'),
('ts.features.BattenedMainsail','it','Randa semi steccata'),
('ts.features.Computer','it','Computer di bordo'),
('ts.features.WindGenerator','nl','Wind generator'),
('ts.features.OutboardEngineBrackets','nl','Buitenboord motorsteunen'),
('ts.features.Trisail','nl','Trysail'),
('ts.features.ElectricHead','nl','Electrische toilet'),
('ts.features.CockpitSpeakers','nl','Cockpit speakers'),
('ts.features.ChemicalHead','nl','Chemisch toilet'),
('ts.features.GenoaCover','nl','Genuahoes'),
('ts.features.Repeater(s)','nl','Aangekoppelde apparaten'),
('ts.features.Tiller','nl','Helmstok'),
('ts.features.Inverter','nl','Omvormer'),
('ts.features.HydraulicWinch','nl','Hydraulische winch'),
('ts.features.Radar','nl','Radar'),
('ts.features.ElectricWinch','nl','Electrische winch'),
('ts.features.TeakCockpit','nl','Teak kuip'),
('ts.features.BatteryCharger','nl','Accu lader'),
('ts.features.IncludesBowsprit','nl','Inclusief boegspriet'),
('ts.features.Log-speedometer','nl','Log'),
('ts.features.Heating','nl','Verwarming'),
('ts.features.MarineHead','nl','Handmatig pomptoilet'),
('ts.features.LaunchingTrailer','nl','Hellingtrailer'),
('ts.features.WashingMachine','nl','Wasmachine'),
('ts.features.Liferaft','nl','Reddingsvlot'),
('ts.features.Generator','nl','Generator'),
('ts.features.SolarPanel','nl','Zonne panelen'),
('ts.features.TeakSidedecks','nl','Teak zijpanelen'),
('ts.features.Dishwasher','nl','Afwasmachine'),
('ts.features.SteeringWheel','nl','Stuurwiel'),
('ts.features.VHF','nl','Marifoon'),
('ts.features.FullyBattenedMainsail','nl','Grootzeil volledig met latten'),
('ts.features.AddDisclaimer','nl','Voeg de disclaimer toe'),
('ts.features.Compass','nl','Kompas'),
('ts.features.CockpitShower','nl','Cockpit douche'),
('ts.features.SpinnakerPole','nl','Spinnakerboom'),
('ts.features.VCR','nl','Videorecorder'),
('ts.features.BowThruster','nl','Boegschroef'),
('ts.features.GennakerCruisingSpinnaker','nl','Gennaker'),
('ts.features.GPS','nl','GPS'),
('ts.features.BeachingLegs','nl','Transportrollen'),
('ts.features.CDPlayer','nl','CD speler'),
('ts.features.Refrigerator','nl','Koelkast'),
('ts.features.AsymetricSpinnaker','nl','Asymetrische spinnaker'),
('ts.features.HydraulicGangway','nl','Hydraulische loopplank'),
('ts.features.SeaWaterPump','nl','Zeewater pomp'),
('ts.features.Spinnaker','nl','Spinnaker'),
('ts.features.StormJib','nl','Stormfok'),
('ts.features.LazyBag','nl','Lazy bag'),
('ts.features.Genoa','nl','Genua'),
('ts.features.Davits','nl','Davits'),
('ts.features.CockpitCushions','nl','Kuip Kussens'),
('ts.features.RoadTrailer','nl','Trailer'),
('ts.features.ShorePowerInlet','nl','Walstroomaansluiting'),
('ts.features.CockpitTable','nl','Cockpit tafel'),
('ts.features.DeepFreezer','nl','Vrieskist'),
('ts.features.FurlingMainsail','nl','Oprolbaar grootzeil'),
('ts.features.AirConditioning','nl','Airconditioning'),
('ts.features.SprayHood','nl','Sprayhood'),
('ts.features.AirCompressor','nl','Lucht compressor'),
('ts.features.MainsailCover','nl','Grootzeil huik'),
('ts.features.TrimTabs','nl','Trimflaps'),
('ts.features.FurlingGenoa','nl','Rol genua'),
('ts.features.NavigationCenter','nl','Navigatiecentrum'),
('ts.features.ElectricBilgePump','nl','Electrische bilge pomp'),
('ts.features.SternThruster','nl','Hekschroef'),
('ts.features.ManualBilgePump','nl','Manuele bilge pomp'),
('ts.features.Depthsounder','nl','Dieptemeter'),
('ts.features.WindspeedAndDirection','nl','Wind meter'),
('ts.features.RopeCutter','nl','Touw snijder'),
('ts.features.CockpitCover','nl','Cockpit dekzeil'),
('ts.features.Oven','nl','Oven'),
('ts.features.Gangway','nl','Loopplank'),
('ts.features.MicrowaveOven','nl','Magnetron'),
('ts.features.Tender','nl','Bijboot'),
('ts.features.ConvertibleSaloon','nl','Salontafel ombouwen tot bed'),
('ts.features.Plotter','nl','Plotter'),
('ts.features.Autopilot','nl','Automatische piloot'),
('ts.features.DVDPlayer','nl','DVD speler'),
('ts.features.SwimmingLadder','nl','Zwem ladder'),
('ts.features.RadarReflector','nl','Radarreflector'),
('ts.features.FreshWaterMaker','nl','Watermaker'),
('ts.features.Lazyjacks','nl','Lazy jacks'),
('ts.features.Radio','nl','Radio'),
('ts.features.HotWater','nl','Warm water'),
('ts.features.RadarDetector','nl','Radar Detector'),
('ts.features.BiminiTop','nl','Bimini'),
('ts.features.TVSet','nl','TV'),
('ts.features.BattenedMainsail','nl','Grootzeil'),
('ts.features.Computer','nl','Navigatiecomputer'),
('ts.features.GPS','ae','GPS'),
('ts.features.WindGenerator','da','Vindgenerator'),
('ts.features.OutboardEngineBrackets','da','Beslag til udenbordsmotor'),
('ts.features.Trisail','da','Stormsejl'),
('ts.features.ElectricHead','da','Elektrisk toilet'),
('ts.features.CockpitSpeakers','da','Cockpit-højttalere'),
('ts.features.ChemicalHead','da','Kemisk toilet'),
('ts.features.GenoaCover','da','Sejlpose (genua)'),
('ts.features.Repeater(s)','da','Repeater(e)'),
('ts.features.Tiller','da','Rorpind'),
('ts.features.Inverter','da','Vekselretter'),
('ts.features.HydraulicWinch','da','Hydraulisk spil'),
('ts.features.Radar','da','Radar'),
('ts.features.ElectricWinch','da','Elektrisk spil'),
('ts.features.TeakCockpit','da','Teak i cockpit'),
('ts.features.BatteryCharger','da','Batterioplader'),
('ts.features.IncludesBowsprit','da','Inkl. bovspryd'),
('ts.features.Log-speedometer','da','Log'),
('ts.features.Heating','da','Opvarmning'),
('ts.features.MarineHead','da','Søtoilet'),
('ts.features.LaunchingTrailer','da','Beddingsvogn'),
('ts.features.WashingMachine','da','Vaskemaskine'),
('ts.features.Liferaft','da','Redningsflåde'),
('ts.features.Generator','da','Generator'),
('ts.features.SolarPanel','da','Solpanel'),
('ts.features.TeakSidedecks','da','Sidedæk i teak'),
('ts.features.Dishwasher','da','Opvaskemaskine'),
('ts.features.SteeringWheel','da','Rat'),
('ts.features.VHF','da','VHF'),
('ts.features.FullyBattenedMainsail','da','Storsejl med gennemgående sejlpind'),
('ts.features.AddDisclaimer','da','Tilføj ansvarsfraskrivelse'),
('ts.features.Compass','da','Kompas'),
('ts.features.CockpitShower','da','Cockpitbruser'),
('ts.features.SpinnakerPole','da','Spilerstage'),
('ts.features.VCR','da','VCR'),
('ts.features.BowThruster','da','Bovpropeller'),
('ts.features.GennakerCruisingSpinnaker','da','Gennaker'),
('ts.features.GPS','da','GPS'),
('ts.features.BeachingLegs','da','Bådstativer'),
('ts.features.CDPlayer','da','Cd-afspiller'),
('ts.features.Refrigerator','da','Køleskab'),
('ts.features.AsymetricSpinnaker','da','Asymmetrisk spiler'),
('ts.features.HydraulicGangway','da','Hydraulisk landgangsbro'),
('ts.features.SeaWaterPump','da','Havvandspumpe'),
('ts.features.Spinnaker','da','Spiler'),
('ts.features.StormJib','da','Stormklyver'),
('ts.features.LazyBag','da','Lazy bag'),
('ts.features.Genoa','da','Genua'),
('ts.features.Davits','da','Davider'),
('ts.features.CockpitCushions','da','Cockpithynder'),
('ts.features.RoadTrailer','da','Bådtrailer'),
('ts.features.ShorePowerInlet','da','Landtilslutning for el'),
('ts.features.CockpitTable','da','Cockpitbord'),
('ts.features.DeepFreezer','da','Dybfryser'),
('ts.features.FurlingMainsail','da','Rullestorsejl'),
('ts.features.AirConditioning','da','Air condition'),
('ts.features.SprayHood','da','Kaleche/sprayhood'),
('ts.features.AirCompressor','da','Kompressor'),
('ts.features.MainsailCover','da','Storsejlspresenning'),
('ts.features.TrimTabs','da','Trimflapper'),
('ts.features.FurlingGenoa','da','Rullegenua'),
('ts.features.NavigationCenter','da','Navigationscenter'),
('ts.features.ElectricBilgePump','da','Elektrisk lænsepumpe'),
('ts.features.SternThruster','da','Agterpropel'),
('ts.features.ManualBilgePump','da','Manuel lænsepumpe'),
('ts.features.Depthsounder','da','Ekkolod'),
('ts.features.WindspeedAndDirection','da','Vindhastighed og -retning'),
('ts.features.RopeCutter','da','Lineskærer'),
('ts.features.CockpitCover','da','Cockpitkaleche'),
('ts.features.Oven','da','Ovn'),
('ts.features.Gangway','da','Landgangsbro'),
('ts.features.MicrowaveOven','da','Mikrobølgeovn'),
('ts.features.Tender','da','Tender (hjælpebåd)'),
('ts.features.ConvertibleSaloon','da','Konvertibel salon'),
('ts.features.Plotter','da','Plotter'),
('ts.features.Autopilot','da','Autopilot'),
('ts.features.DVDPlayer','da','Dvd-afspiller'),
('ts.features.SwimmingLadder','da','Badelejder'),
('ts.features.RadarReflector','da','Radarreflektor'),
('ts.features.FreshWaterMaker','da','Ferskvandsmaskine'),
('ts.features.Lazyjacks','da','Lazyjack storsejlspose'),
('ts.features.Radio','da','Radio'),
('ts.features.HotWater','da','Varmt vand'),
('ts.features.RadarDetector','da','Radardetektor'),
('ts.features.BiminiTop','da','Bimini-top'),
('ts.features.TVSet','da','Tv'),
('ts.features.BattenedMainsail','da','Storsejl med sejlpind'),
('ts.features.Computer','da','Computer'),
('ts.features.WindGenerator','sv','Vindgenerator'),
('ts.features.OutboardEngineBrackets','sv','Fäste för utombordsmotor'),
('ts.features.Trisail','sv','Stormsegel (stor)'),
('ts.features.ElectricHead','sv','Eltoalett'),
('ts.features.CockpitSpeakers','sv','Cockpithögtalare'),
('ts.features.ChemicalHead','sv','Kemisk toalett'),
('ts.features.GenoaCover','sv','Genuaskydd'),
('ts.features.Repeater(s)','sv','Repeater'),
('ts.features.Tiller','sv','Rorkult'),
('ts.features.Inverter','sv','Inverter'),
('ts.features.HydraulicWinch','sv','Hydraulisk winsch'),
('ts.features.Radar','sv','Radar'),
('ts.features.ElectricWinch','sv','Elektrisk vinsch'),
('ts.features.TeakCockpit','sv','Teak i sittbrunn'),
('ts.features.BatteryCharger','sv','Batteriladdare'),
('ts.features.IncludesBowsprit','sv','Inklusive bogspröt'),
('ts.features.Log-speedometer','sv','Logg'),
('ts.features.Heating','sv','Värmare'),
('ts.features.MarineHead','sv','Marintoalett'),
('ts.features.LaunchingTrailer','sv','Sjösättningsvagn'),
('ts.features.WashingMachine','sv','Tvättmaskin'),
('ts.features.Liferaft','sv','Räddningsflotte'),
('ts.features.Generator','sv','Generator'),
('ts.features.SolarPanel','sv','Solpanel'),
('ts.features.TeakSidedecks','sv','Teakdäck'),
('ts.features.Dishwasher','sv','Diskmaskin'),
('ts.features.SteeringWheel','sv','Ratt'),
('ts.features.VHF','sv','VHF'),
('ts.features.FullyBattenedMainsail','sv','Full-latte storsegel'),
('ts.features.AddDisclaimer','sv','Lägg till friskrivningsklausul'),
('ts.features.Compass','sv','Kompass'),
('ts.features.CockpitShower','sv','Dusch i sittbrunn'),
('ts.features.SpinnakerPole','sv','Spinnakerbom'),
('ts.features.VCR','sv','Video'),
('ts.features.BowThruster','sv','Bogpropeller'),
('ts.features.GennakerCruisingSpinnaker','sv','Gennaker'),
('ts.features.GPS','sv','GPS'),
('ts.features.BeachingLegs','sv','Stöttor för uppallning'),
('ts.features.CDPlayer','sv','CD-spelare'),
('ts.features.Refrigerator','sv','Kylskåp'),
('ts.features.AsymetricSpinnaker','sv','Asymmetrisk spinnaker'),
('ts.features.HydraulicGangway','sv','Hydraulisk landgång'),
('ts.features.SeaWaterPump','sv','Sjövattenpump'),
('ts.features.Spinnaker','sv','Spinnaker'),
('ts.features.StormJib','sv','Stormfock'),
('ts.features.LazyBag','sv','Lazybag'),
('ts.features.Genoa','sv','Genua'),
('ts.features.Davits','sv','Dävertar'),
('ts.features.CockpitCushions','sv','Sittbrunnsdynor'),
('ts.features.RoadTrailer','sv','Släpvagn'),
('ts.features.ShorePowerInlet','sv','Landströms anslutning'),
('ts.features.CockpitTable','sv','Sittbrunnsbord'),
('ts.features.DeepFreezer','sv','Frys'),
('ts.features.FurlingMainsail','sv','Rullstorsegel'),
('ts.features.AirConditioning','sv','Luftkonditionering'),
('ts.features.SprayHood','sv','Sprayhood'),
('ts.features.AirCompressor','sv','Luftkompressor'),
('ts.features.MainsailCover','sv','Storsegelkapell'),
('ts.features.TrimTabs','sv','Trimroder'),
('ts.features.FurlingGenoa','sv','Rull focks system'),
('ts.features.NavigationCenter','sv','Navigationscenter'),
('ts.features.ElectricBilgePump','sv','Elektrisk länspump'),
('ts.features.SternThruster','sv','Häckpropeller'),
('ts.features.ManualBilgePump','sv','Manuell länspump'),
('ts.features.Depthsounder','sv','Eko lod'),
('ts.features.WindspeedAndDirection','sv','Vindmätare'),
('ts.features.RopeCutter','sv','Repavskärare'),
('ts.features.CockpitCover','sv','Sittbrunnstält'),
('ts.features.Oven','sv','Ugn'),
('ts.features.Gangway','sv','Landgång'),
('ts.features.MicrowaveOven','sv','Mikrougn'),
('ts.features.Tender','sv','Tenderbåt'),
('ts.features.ConvertibleSaloon','sv','Bäddbar salong'),
('ts.features.Plotter','sv','Kart plotter'),
('ts.features.Autopilot','sv','Autopilot'),
('ts.features.DVDPlayer','sv','DVD-spelare'),
('ts.features.SwimmingLadder','sv','Badstege'),
('ts.features.RadarReflector','sv','Radarreflektor'),
('ts.features.FreshWaterMaker','sv','Rullgenua'),
('ts.features.Lazyjacks','sv','Lazy jacks'),
('ts.features.Radio','sv','Radio'),
('ts.features.HotWater','sv','Varmvatten'),
('ts.features.RadarDetector','sv','Radardetektor'),
('ts.features.BiminiTop','sv','Bimini'),
('ts.features.TVSet','sv','TV'),
('ts.features.BattenedMainsail','sv','Lattor i storsegel'),
('ts.features.Computer','sv','Dator'),
('ts.features.WindGenerator','fi','Tuuligeneraattori'),
('ts.features.OutboardEngineBrackets','fi','Perämoottoriteline'),
('ts.features.Trisail','fi','Trisail'),
('ts.features.ElectricHead','fi','Sähköinen WC'),
('ts.features.CockpitSpeakers','fi','Avotilan kaiuttimet'),
('ts.features.ChemicalHead','fi','Kemiallinen WC'),
('ts.features.GenoaCover','fi','Genoan suoja'),
('ts.features.Repeater(s)','fi','Näytöt'),
('ts.features.Tiller','fi','Peräsinpinna'),
('ts.features.Inverter','fi','Invertteri'),
('ts.features.HydraulicWinch','fi','Hydraulivinssi'),
('ts.features.Radar','fi','Tutka'),
('ts.features.ElectricWinch','fi','Sähkövinssi'),
('ts.features.TeakCockpit','fi','Tiikki avotilassa'),
('ts.features.BatteryCharger','fi','Akkulaturi'),
('ts.features.IncludesBowsprit','fi','Sisältää keulapuomin'),
('ts.features.Log-speedometer','fi','Loki-Nopeus'),
('ts.features.Heating','fi','Lämmitys'),
('ts.features.MarineHead','fi','Vesi WC'),
('ts.features.LaunchingTrailer','fi','Vesillelasku traileri'),
('ts.features.WashingMachine','fi','Pesukone'),
('ts.features.Liferaft','fi','Pelastuslautta'),
('ts.features.Generator','fi','Generaattori'),
('ts.features.SolarPanel','fi','Aurinkopaneeli'),
('ts.features.TeakSidedecks','fi','Tiikki sivukansilla'),
('ts.features.Dishwasher','fi','Tiskikone'),
('ts.features.SteeringWheel','fi','Ruori'),
('ts.features.VHF','fi','VHF'),
('ts.features.FullyBattenedMainsail','fi','Läpilatta isopurje'),
('ts.features.AddDisclaimer','fi','Lisää vastuuvapauslauseke'),
('ts.features.Compass','fi','Kompassi'),
('ts.features.CockpitShower','fi','Avotilan suihku'),
('ts.features.SpinnakerPole','fi','Spinakkeerin puomi'),
('ts.features.VCR','fi','Videot'),
('ts.features.BowThruster','fi','Keulapotkuri'),
('ts.features.GennakerCruisingSpinnaker','fi','Genaakkeri/Cruising Spinnu'),
('ts.features.GPS','fi','GPS'),
('ts.features.BeachingLegs','fi','Rantautumisjalat'),
('ts.features.CDPlayer','fi','CD soitin'),
('ts.features.Refrigerator','fi','Jääkaappi'),
('ts.features.AsymetricSpinnaker','fi','Asymmetrinen spinaakkeri'),
('ts.features.HydraulicGangway','fi','Hydraulinen lankonki'),
('ts.features.SeaWaterPump','fi','Merivesipumppu'),
('ts.features.Spinnaker','fi','Spinaakkeri'),
('ts.features.StormJib','fi','Myrskyfokka'),
('ts.features.LazyBag','fi','Lazy bag'),
('ts.features.Genoa','fi','Genoa'),
('ts.features.Davits','fi','Taavetit'),
('ts.features.CockpitCushions','fi','Avotilan tyynyt'),
('ts.features.RoadTrailer','fi','Maantietraileri'),
('ts.features.ShorePowerInlet','fi','Maasähköpistoke'),
('ts.features.CockpitTable','fi','Avotilan pöytä'),
('ts.features.DeepFreezer','fi','Pakastin'),
('ts.features.FurlingMainsail','fi','Rullaiso'),
('ts.features.AirConditioning','fi','Ilmastointi'),
('ts.features.SprayHood','fi','Sprayhood'),
('ts.features.AirCompressor','fi','Ilmakompressori'),
('ts.features.MainsailCover','fi','Isonpurjeen peite'),
('ts.features.TrimTabs','fi','Trimmitasot'),
('ts.features.FurlingGenoa','fi','Rullagenoa'),
('ts.features.NavigationCenter','fi','Navigaatio keskus'),
('ts.features.ElectricBilgePump','fi','Sähköinen pilssipumppu'),
('ts.features.SternThruster','fi','Peräpotkuri'),
('ts.features.ManualBilgePump','fi','Käsikäyttöinen pilssipumppu'),
('ts.features.Depthsounder','fi','Kaikuluotain'),
('ts.features.WindspeedAndDirection','fi','Tuulennopeus ja -suunta'),
('ts.features.RopeCutter','fi','Potkuriakselin Köysileikkuri'),
('ts.features.CockpitCover','fi','Avotilan peite'),
('ts.features.Oven','fi','Uuni'),
('ts.features.Gangway','fi','Lankonki'),
('ts.features.MicrowaveOven','fi','Mikroaaltouuni'),
('ts.features.Tender','fi','Apuvene'),
('ts.features.ConvertibleSaloon','fi','Muunneltava salonki'),
('ts.features.Plotter','fi','Plotteri'),
('ts.features.Autopilot','fi','Autopilotti'),
('ts.features.DVDPlayer','fi','DVD soitin'),
('ts.features.SwimmingLadder','fi','Uimaportaat'),
('ts.features.RadarReflector','fi','Tutkaheijastin'),
('ts.features.FreshWaterMaker','fi','Vedentekokone'),
('ts.features.Lazyjacks','fi','Lazyjacks'),
('ts.features.Radio','fi','Radio'),
('ts.features.HotWater','fi','Kuuma vesi'),
('ts.features.RadarDetector','fi','Tutkan Ilmaisin'),
('ts.features.BiminiTop','fi','Bimini'),
('ts.features.TVSet','fi','TV setti'),
('ts.features.BattenedMainsail','fi','Latoitettu isopurje'),
('ts.features.Computer','fi','Tietokone'),
('ts.features.WindGenerator','no','Vindgenerator'),
('ts.features.OutboardEngineBrackets','no','Feste for påhengsmotor'),
('ts.features.Trisail','no','Tryseil'),
('ts.features.ElectricHead','no','Elektrisk toalett'),
('ts.features.CockpitSpeakers','no','Cockpithøytalere'),
('ts.features.ChemicalHead','no','Kjemisk toalett'),
('ts.features.GenoaCover','no','Genoa trekk'),
('ts.features.Repeater(s)','no','Gjentager(e)'),
('ts.features.Tiller','no','Rorpinne'),
('ts.features.Inverter','no','Inverterer'),
('ts.features.HydraulicWinch','no','Hydraulisk vinsj'),
('ts.features.Radar','no','Radar'),
('ts.features.ElectricWinch','no','Elektrisk vinsj'),
('ts.features.TeakCockpit','no','Teakcockpit'),
('ts.features.BatteryCharger','no','Batterilader'),
('ts.features.IncludesBowsprit','no','Inkludert Baugspyd'),
('ts.features.Log-speedometer','no','Logg-speedometer'),
('ts.features.Heating','no','Oppvarming'),
('ts.features.MarineHead','no','Båt-toalett'),
('ts.features.LaunchingTrailer','no','Båt trailer'),
('ts.features.WashingMachine','no','Vaskemaskin'),
('ts.features.Liferaft','no','Livbåt'),
('ts.features.Generator','no','Generator'),
('ts.features.SolarPanel','no','Solsellepanel'),
('ts.features.TeakSidedecks','no','Teaksider'),
('ts.features.Dishwasher','no','Oppvaskmaskin'),
('ts.features.SteeringWheel','no','Ror'),
('ts.features.VHF','no','VHF'),
('ts.features.FullyBattenedMainsail','no','Fullt forsterket storseil'),
('ts.features.AddDisclaimer','no','Legg til ansvarsfraskrivelse'),
('ts.features.Compass','no','Kompass'),
('ts.features.CockpitShower','no','Cockpitdusj'),
('ts.features.SpinnakerPole','no','Spinnakermast'),
('ts.features.VCR','no','VCR'),
('ts.features.BowThruster','no','Baugpropell'),
('ts.features.GennakerCruisingSpinnaker','no','Gennaker'),
('ts.features.GPS','no','GPS'),
('ts.features.BeachingLegs','no','Strandben'),
('ts.features.CDPlayer','no','CD spiller'),
('ts.features.Refrigerator','no','Kjøleskap'),
('ts.features.AsymetricSpinnaker','no','Asymmetrisk spinnaker'),
('ts.features.HydraulicGangway','no','Hydraulisk landgang'),
('ts.features.SeaWaterPump','no','Sjøvannspumpe'),
('ts.features.Spinnaker','no','Spinnaker'),
('ts.features.StormJib','no','Storm jibb'),
('ts.features.LazyBag','no','Lazybag'),
('ts.features.Genoa','no','Genoa'),
('ts.features.Davits','no','Daviter'),
('ts.features.CockpitCushions','no','Cockpitputer'),
('ts.features.RoadTrailer','no','Trailer'),
('ts.features.ShorePowerInlet','no','Landstrømlader'),
('ts.features.CockpitTable','no','Cockpitbord'),
('ts.features.DeepFreezer','no','Fryseboks'),
('ts.features.FurlingMainsail','no','Furling storseil'),
('ts.features.AirConditioning','no','Luftkondisjonering'),
('ts.features.SprayHood','no','Beskytter mot sjøsprøyt'),

('ts.features.AirCompressor','no','Luftkompressor'),
('ts.features.MainsailCover','no','Storseiltrekk'),
('ts.features.TrimTabs','no','Trimklaff'),
('ts.features.FurlingGenoa','no','Furling genoa'),
('ts.features.NavigationCenter','no','Navigasjonsplass'),
('ts.features.ElectricBilgePump','no','Elektrisk lensepumpe'),
('ts.features.SternThruster','no','Akterpropell'),
('ts.features.ManualBilgePump','no','Manuell lensepumpe'),
('ts.features.Depthsounder','no','Dybdemåler'),
('ts.features.WindspeedAndDirection','no','Vind hastighet og retning'),
('ts.features.RopeCutter','no','Taukutter'),
('ts.features.CockpitCover','no','Cockpitdeksel'),
('ts.features.Oven','no','Ovn'),
('ts.features.Gangway','no','Landgang'),
('ts.features.MicrowaveOven','no','Mikrobølgeovn'),
('ts.features.Tender','no','Tender'),
('ts.features.ConvertibleSaloon','no','Konvertibel Salong'),
('ts.features.Plotter','no','Plotter'),
('ts.features.Autopilot','no','Autopilot'),
('ts.features.DVDPlayer','no','DVD-spiller'),
('ts.features.SwimmingLadder','no','Svømmestige'),
('ts.features.RadarReflector','no','Radar reflektor'),
('ts.features.FreshWaterMaker','no','Ferskvannsmaskin'),
('ts.features.Lazyjacks','no','Lazyjacks'),
('ts.features.Radio','no','Radio'),
('ts.features.HotWater','no','Varmvann'),
('ts.features.RadarDetector','no','Radar Detektor'),
('ts.features.BiminiTop','no','Bimini Topp'),
('ts.features.TVSet','no','TV sett'),
('ts.features.BattenedMainsail','no','Forsterket storseil'),
('ts.features.Computer','no','Datamaskin'),
('ts.features.WindGenerator','ru','Ветрогенератор'),
('ts.features.OutboardEngineBrackets','ru','Кронштейны подвесного мотора'),
('ts.features.Trisail','ru','Штормовой парус (Trysail)'),
('ts.features.ElectricHead','ru','Электрический приемник'),
('ts.features.CockpitSpeakers','ru','Динамики в кокпите'),
('ts.features.ChemicalHead','ru','Химическая головка'),
('ts.features.GenoaCover','ru','Перекрытие генуэзского стакселя'),
('ts.features.Repeater(s)','ru','Репитер(ы)'),
('ts.features.Tiller','ru','Румпель'),
('ts.features.Inverter','ru','Инвертер'),
('ts.features.HydraulicWinch','ru','Гидравлическая лебедка'),
('ts.features.Radar','ru','Радар'),
('ts.features.ElectricWinch','ru','Электрическая лебедка'),
('ts.features.TeakCockpit','ru','Тиковый кокпит'),
('ts.features.BatteryCharger','ru','Зарядное устройство'),
('ts.features.IncludesBowsprit','ru','Включая бушприт'),
('ts.features.Log-speedometer','ru','Лаг'),
('ts.features.Heating','ru','Обогрев'),
('ts.features.MarineHead','ru','Санузел'),
('ts.features.LaunchingTrailer','ru','Трейлер'),
('ts.features.WashingMachine','ru','Стиральная машина'),
('ts.features.Liferaft','ru','Спасательный плот'),
('ts.features.Generator','ru','Генератор'),
('ts.features.SolarPanel','ru','Солнечная панель'),
('ts.features.TeakSidedecks','ru','Тиковые потопчины'),
('ts.features.Dishwasher','ru','Посудомоечная машина'),
('ts.features.SteeringWheel','ru','Штурвал'),
('ts.features.VHF','ru','УКВ'),
('ts.features.FullyBattenedMainsail','ru','Грот со сквозными латами'),
('ts.features.AddDisclaimer','ru','Добавить заявление об ограничении ответственности'),
('ts.features.Compass','ru','Компас'),
('ts.features.CockpitShower','ru','Душ в кокпите'),
('ts.features.SpinnakerPole','ru','Спинакер-гик'),
('ts.features.VCR','ru','Видеомагнитофон'),
('ts.features.BowThruster','ru','Носовые подруливающие устройства'),
('ts.features.GennakerCruisingSpinnaker','ru','Геннакер/Крейсерский спинакер'),
('ts.features.GPS','ru','гсп'),
('ts.features.BeachingLegs','ru','Береговые стойки'),
('ts.features.CDPlayer','ru','Проигрыватель CD'),
('ts.features.Refrigerator','ru','Холодильник'),
('ts.features.AsymetricSpinnaker','ru','Асимметричный спинакер'),
('ts.features.HydraulicGangway','ru','Гидравлический трап'),
('ts.features.SeaWaterPump','ru','Насос забортной воды'),
('ts.features.Spinnaker','ru','Спинакер'),
('ts.features.StormJib','ru','Штормовой стаксель'),
('ts.features.LazyBag','ru','Автоматическое рифление (Lazy bag)'),
('ts.features.Genoa','ru','Генуэзский стаксель'),
('ts.features.Davits','ru','Шлюпбалки'),
('ts.features.CockpitCushions','ru','Сиденья кокпита'),
('ts.features.RoadTrailer','ru','Автомобильный прицеп'),
('ts.features.ShorePowerInlet','ru','Электрический разъем для подключения на берегу'),
('ts.features.CockpitTable','ru','Стол в кокпите'),
('ts.features.DeepFreezer','ru','Морозильная камера'),
('ts.features.FurlingMainsail','ru','Закрутка грота'),
('ts.features.AirConditioning','ru','Кондиционер'),
('ts.features.SprayHood','ru','Брызгозащитный козырек'),
('ts.features.AirCompressor','ru','Воздушный компрессор'),
('ts.features.MainsailCover','ru','Чехол грота'),
('ts.features.TrimTabs','ru','Триммер'),
('ts.features.FurlingGenoa','ru','Закрутка генуи'),
('ts.features.NavigationCenter','ru','Навигационный центр'),
('ts.features.ElectricBilgePump','ru','Электрическая трюмная помпа'),
('ts.features.SternThruster','ru','Кормовое подруливающее устройство'),
('ts.features.ManualBilgePump','ru','Ручная трюмная помпа'),
('ts.features.Depthsounder','ru','Эхолот'),
('ts.features.WindspeedAndDirection','ru','Скорость и направление ветра'),
('ts.features.RopeCutter','ru','Резец для канатов'),
('ts.features.CockpitCover','ru','Кожух кокпита'),
('ts.features.Oven','ru','Плита'),
('ts.features.Gangway','ru','Трап'),
('ts.features.MicrowaveOven','ru','СВЧ-печь'),
('ts.features.Tender','ru','Шлюбка'),
('ts.features.ConvertibleSaloon','ru','Трансформируемая кают-компания'),
('ts.features.Plotter','ru','Курсограф'),
('ts.features.Autopilot','ru','Автопилот'),
('ts.features.DVDPlayer','ru','Проигрыватель DVD'),
('ts.features.SwimmingLadder','ru','Палуба для купания'),
('ts.features.RadarReflector','ru','Радиолокационный отражатель'),
('ts.features.FreshWaterMaker','ru','Опреснитель воды'),
('ts.features.Lazyjacks','ru','Приспособления для рифления (Lazyjack)'),
('ts.features.Radio','ru','Радио'),
('ts.features.HotWater','ru','Горячая вода'),
('ts.features.RadarDetector','ru','Радарный детектор'),
('ts.features.BiminiTop','ru','Навесной тент'),
('ts.features.TVSet','ru','Телевизор'),
('ts.features.BattenedMainsail','ru','Грот с латами'),
('ts.features.Computer','ru','Компьютер'),
('ts.feature_category.OutsideEquipmentExtras','en','Outside Equipment/Extras'),
('ts.feature_category.Disclaimer','en','Disclaimer'),
('ts.feature_category.Rigging','en','Rigging'),
('ts.feature_category.AdditionalEquipment','en','Additional Equipment'),
('ts.feature_category.Tanks','en','Tanks'),
('ts.feature_category.BoatName','en','Boat Name'),
('ts.feature_category.Accommodation','en','Accommodations'),
('ts.feature_category.Sails','en','Sails'),
('ts.feature_category.Covers','en','Covers'),
('ts.feature_category.ElectricalEquipment','en','Electrical Equipment'),
('ts.feature_category.Specs','en','Specs'),
('ts.feature_category.InsideEquipment','en','Inside Equipment'),
('ts.feature_category.Engines','en','Engines'),
('ts.feature_category.Electronics','en','Electronics'),
('ts.feature_category.Dimensions','en','Dimensions'),
('ts.feature_category.OutsideEquipmentExtras','uk','Outside Equipment/Extras'),
('ts.feature_category.Disclaimer','uk','Disclaimer'),
('ts.feature_category.Rigging','uk','Rigging'),
('ts.feature_category.AdditionalEquipment','uk','Additional Equipment'),
('ts.feature_category.Tanks','uk','Tanks'),
('ts.feature_category.BoatName','uk','Boat Name'),
('ts.feature_category.Accommodation','uk','Accommodation'),
('ts.feature_category.Sails','uk','Sails'),
('ts.feature_category.Covers','uk','Covers'),
('ts.feature_category.ElectricalEquipment','uk','Electrical Equipment'),
('ts.feature_category.Specs','uk','Specs'),
('ts.feature_category.InsideEquipment','uk','Inside Equipment'),
('ts.feature_category.Engines','uk','Engines'),
('ts.feature_category.Electronics','uk','Electronics'),
('ts.feature_category.Dimensions','uk','Dimensions'),
('ts.feature_category.OutsideEquipmentExtras','fr','Équipement Extérieur/Options'),
('ts.feature_category.Disclaimer','fr','Avis de Non-responsabilité'),
('ts.feature_category.Rigging','fr','Accastilage/Gréement'),
('ts.feature_category.AdditionalEquipment','fr','Équipement Supplémentaire'),
('ts.feature_category.Tanks','fr','Réservoirs'),
('ts.feature_category.BoatName','fr','Nom du Bateau'),
('ts.feature_category.Accommodation','fr','Aménagement'),
('ts.feature_category.Sails','fr','Voiles'),
('ts.feature_category.Covers','fr','Tauds'),
('ts.feature_category.ElectricalEquipment','fr','Appareillage Électrique'),
('ts.feature_category.Specs','fr','Spécifications'),
('ts.feature_category.InsideEquipment','fr','Équipement Interieur'),
('ts.feature_category.Engines','fr','Motorisation'),
('ts.feature_category.Electronics','fr','Électronique'),
('ts.feature_category.Dimensions','fr','Dimensions'),
('ts.feature_category.OutsideEquipmentExtras','de','Deckausstattung'),
('ts.feature_category.Disclaimer','de','Haftungsausschluss'),
('ts.feature_category.Rigging','de','Takelage'),
('ts.feature_category.AdditionalEquipment','de','Zusätzliche Ausstattung'),
('ts.feature_category.Tanks','de','Tanks'),
('ts.feature_category.BoatName','de','Name des Schiffes'),
('ts.feature_category.Accommodation','de','Kabinen'),
('ts.feature_category.Sails','de','Besegelung'),
('ts.feature_category.Covers','de','Verdecke'),
('ts.feature_category.ElectricalEquipment','de','Elektrische Ausstattung'),
('ts.feature_category.Specs','de','Spez.'),
('ts.feature_category.InsideEquipment','de','Innenausstattung'),
('ts.feature_category.Engines','de','Maschine'),
('ts.feature_category.Electronics','de','Elektronik'),
('ts.feature_category.Dimensions','de','Maße'),
('ts.feature_category.OutsideEquipmentExtras','es','Equipamiento Exterior'),
('ts.feature_category.Disclaimer','es','Exención de Responsabilidades'),
('ts.feature_category.Rigging','es','Aparejo'),
('ts.feature_category.AdditionalEquipment','es','Equipamiento Adicional'),
('ts.feature_category.Tanks','es','Depósitos'),
('ts.feature_category.BoatName','es','Nombre del Barco'),
('ts.feature_category.Accommodation','es','Alojamiento'),
('ts.feature_category.Sails','es','Velas'),
('ts.feature_category.Covers','es','Toldos'),
('ts.feature_category.ElectricalEquipment','es','Equipo Eléctrico'),
('ts.feature_category.Specs','es','Características'),
('ts.feature_category.InsideEquipment','es','Equipamiento Interior'),
('ts.feature_category.Engines','es','Motorización'),
('ts.feature_category.Electronics','es','Electrónica'),
('ts.feature_category.Dimensions','es','Dimensiones'),
('ts.feature_category.OutsideEquipmentExtras','it','Dotazioni Esterne'),
('ts.feature_category.Disclaimer','it','Declinazione di responsabilità '),
('ts.feature_category.Rigging','it','Attrezzatura/Dotazioni'),
('ts.feature_category.AdditionalEquipment','it','Dotazioni Addizionali'),
('ts.feature_category.Tanks','it','Serbatoi'),
('ts.feature_category.BoatName','it','Nome della Barca'),
('ts.feature_category.Accommodation','it','Interni'),
('ts.feature_category.Sails','it','Vele'),
('ts.feature_category.Covers','it','Coperture/Tendalini'),
('ts.feature_category.ElectricalEquipment','it','Equipaggiamenti Elettrici'),
('ts.feature_category.Specs','it','Caratteristiche'),
('ts.feature_category.InsideEquipment','it','Equipaggiamenti interni'),
('ts.feature_category.Engines','it','Motori'),
('ts.feature_category.Electronics','it','Elettronici'),
('ts.feature_category.Dimensions','it','Dimensioni'),
('ts.feature_category.OutsideEquipmentExtras','nl','Uitrusting Buiten'),
('ts.feature_category.Disclaimer','nl','Disclaimer'),
('ts.feature_category.Rigging','nl','Tuigage'),
('ts.feature_category.AdditionalEquipment','nl','Extra Uitrusting'),
('ts.feature_category.Tanks','nl','Tanks'),
('ts.feature_category.BoatName','nl','Naam van Boot'),
('ts.feature_category.Accommodation','nl','Interieur'),
('ts.feature_category.Sails','nl','Zeilen'),
('ts.feature_category.Covers','nl','Hoezen'),
('ts.feature_category.ElectricalEquipment','nl','Electrische Uitrusting'),
('ts.feature_category.Specs','nl','Specificaties'),
('ts.feature_category.InsideEquipment','nl','Uitrusting Binnen'),
('ts.feature_category.Engines','nl','Motor'),
('ts.feature_category.Electronics','nl','Installaties'),
('ts.feature_category.Dimensions','nl','Afmetingen'),
('ts.feature_category.OutsideEquipmentExtras','da','Udenbordsudstyr/Ekstraudstyr'),
('ts.feature_category.Disclaimer','da','Ansvarsfraskrivelse'),
('ts.feature_category.Rigging','da','Takkelage'),
('ts.feature_category.AdditionalEquipment','da','Yderligere udstyr'),
('ts.feature_category.Tanks','da','Tanke'),
('ts.feature_category.BoatName','da','Bådnavn'),
('ts.feature_category.Accommodation','da','Aptering'),
('ts.feature_category.Sails','da','Sejl'),
('ts.feature_category.Covers','da','Overdækning'),
('ts.feature_category.ElectricalEquipment','da','Elektrisk udstyr'),
('ts.feature_category.Specs','da','Specifikationer'),
('ts.feature_category.InsideEquipment','da','Interiør'),
('ts.feature_category.Engines','da','Motorer'),
('ts.feature_category.Electronics','da','Elektronik'),
('ts.feature_category.Dimensions','da','Mål'),
('ts.feature_category.OutsideEquipmentExtras','sv','Däcksutrustning/Extra'),
('ts.feature_category.Disclaimer','sv','Friskrivningsklausul'),
('ts.feature_category.Rigging','sv','Rigg'),
('ts.feature_category.AdditionalEquipment','sv','Tilläggsutrustning'),
('ts.feature_category.Tanks','sv','Tankar'),
('ts.feature_category.BoatName','sv','Båtens namn'),
('ts.feature_category.Accommodation','sv','Boutrymme'),
('ts.feature_category.Sails','sv','Segel'),
('ts.feature_category.Covers','sv','Presenningar'),
('ts.feature_category.ElectricalEquipment','sv','Elutrustning'),
('ts.feature_category.Specs','sv','Specifikationer'),
('ts.feature_category.InsideEquipment','sv','Inre utrustning'),
('ts.feature_category.Engines','sv','Motorer'),
('ts.feature_category.Electronics','sv','Elektronik'),
('ts.feature_category.Dimensions','sv','Dimensioner'),
('ts.feature_category.OutsideEquipmentExtras','fi','Ulkovarusteet/Extrat'),
('ts.feature_category.Disclaimer','fi','Vastuuvapauslauseke'),
('ts.feature_category.Rigging','fi','Riki'),
('ts.feature_category.AdditionalEquipment','fi','Lisävarusteet'),
('ts.feature_category.Tanks','fi','Säiliöt'),
('ts.feature_category.BoatName','fi','Veneen Nimi'),
('ts.feature_category.Accommodation','fi','Mukavuudet'),
('ts.feature_category.Sails','fi','Purjeet'),
('ts.feature_category.Covers','fi','Peitteet'),
('ts.feature_category.ElectricalEquipment','fi','Sähkövarusteet'),
('ts.feature_category.Specs','fi','Tiedot'),
('ts.feature_category.InsideEquipment','fi','Sisävarusteet'),
('ts.feature_category.Engines','fi','Moottorit'),
('ts.feature_category.Electronics','fi','Elektroniikka'),
('ts.feature_category.Dimensions','fi','Mitat'),
('ts.feature_category.OutsideEquipmentExtras','no','Utendørsutstyr/Tillegsutstyr'),
('ts.feature_category.Disclaimer','no','Ansvarsfraskrivelse'),
('ts.feature_category.Rigging','no','Rigging'),
('ts.feature_category.AdditionalEquipment','no','Tilleggsutstyr'),
('ts.feature_category.Tanks','no','Tanker'),
('ts.feature_category.BoatName','no','Båtnavn'),
('ts.feature_category.Accommodation','no','Losji'),
('ts.feature_category.Sails','no','Seil'),
('ts.feature_category.Covers','no','Dekke'),
('ts.feature_category.ElectricalEquipment','no','Elektrisk utstyr'),
('ts.feature_category.Specs','no','Spesifikasjoner'),
('ts.feature_category.InsideEquipment','no','Innendørs utstyr'),
('ts.feature_category.Engines','no','Motorer'),
('ts.feature_category.Electronics','no','Elektronikk'),
('ts.feature_category.Dimensions','no','Dimensjoner'),
('ts.feature_category.OutsideEquipmentExtras','ru','Внешнее и дополнительное оборудование'),
('ts.feature_category.Disclaimer','ru','Заявление об ограничении ответственности'),
('ts.feature_category.Rigging','ru','Такелаж'),
('ts.feature_category.AdditionalEquipment','ru','Дополнительное оборудование'),
('ts.feature_category.Tanks','ru','Баки'),
('ts.feature_category.BoatName','ru','Название судна'),
('ts.feature_category.Accommodation','ru','Размещение'),

('ts.feature_category.Sails','ru','Паруса'),
('ts.feature_category.Covers','ru','Тенты'),
('ts.feature_category.ElectricalEquipment','ru','Электрооборудование'),
('ts.feature_category.Specs','ru','Спецификации'),
('ts.feature_category.InsideEquipment','ru','Внутреннее оборудование'),
('ts.feature_category.Engines','ru','Двигатели'),
('ts.feature_category.Electronics','ru','Электроника'),
('ts.feature_category.Dimensions','ru','Размеры');";

$result = $db->db_query($query);
if (!$result){ 
	die ("Database access failed12");
}else{ 
	echo "Tables created successfully";
}

?>

